### ISSUE TITLE
Memcache errors

### ISSUE THREAD

**Issue by stuartshields** [Chassis/memcache#23]
Since yesterdays update the memcache extension seems to be broken even with Robs changes. Here is the error log attached
[php_errors.log](https://github.com/Chassis/memcache/files/1813519/php_errors.log)

**Comment by stuartshields** [comment]
@BronsonQuick when testing have a look at the client Project setup. Will add more information here as I come across the extra errors.

**Comment by roborourke** [comment]
@stuartshields all I did was fix the provisioning step, you might still need to include the `object-cache.php` file and configure the memcached hosts global

**Comment by BronsonQuick** [comment]
I think this was a project setup issue.
